using System.Globalization;

namespace PhoneDock.Core;

/// Display strings only. Protocol keys, identifiers and user-created content are never translated.
public static class AppLanguage
{
    private static string selected = "system";
    public static string Selected {
        get => selected;
        set => selected = value is "en" or "es" ? value : "system";
    }
    public static string Resolve(string choice, string systemLanguage) => choice is "en" or "es" ? choice : systemLanguage.StartsWith("es", StringComparison.OrdinalIgnoreCase) ? "es" : "en";
    public static string Code => Resolve(Selected, CultureInfo.CurrentUICulture.Name);
    public static string T(string text) => Code == "en" ? English.GetValueOrDefault(text, text) : text;
    public static string F(string text, params object[] values) => string.Format(CultureInfo.GetCultureInfo(Code), T(text), values);
    internal static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string> {
        ["La aplicación ya está abierta, pero Windows bloqueó el cambio de ventana. Selecciónala en la barra de tareas; no se abrió otra instancia."] = "The application is already open, but Windows blocked switching windows. Select it on the taskbar; no other instance was opened.",
        ["Este acceso directo no apunta a un ejecutable. Selecciona el archivo .exe de la aplicación para poder cambiar a su ventana."] = "This shortcut does not point to an executable. Select the application's .exe file to switch to its window.",
        ["Inicio"] = "Home",
        ["Mi Dock"] = "My Dock",
        ["Dispositivos"] = "Devices",
        ["Apariencia"] = "Appearance",
        ["Acerca de"] = "About",
        ["Tu estudio personal"] = "Your personal studio",
        ["WINDOWS · LOCAL · TUYO"] = "WINDOWS · LOCAL · YOURS",
        ["Cerrar"] = "Dismiss",
        ["Conexión detenida"] = "Connection stopped",
        ["Listo para conectar"] = "Ready to connect",
        ["{0} dispositivo(s) conectado(s)"] = "{0} connected device(s)",
        ["Tu PC, a un toque."] = "Your PC, one tap away.",
        ["Un espacio personal para tus acciones de cada día."] = "A personal space for your everyday actions.",
        ["Mejor juntos."] = "Better together.",
        ["Abre Phone Dock en tu iPhone, entra en Dispositivos y elige este PC. También puedes conectarte con su dirección IP."] = "Open Phone Dock on your iPhone, go to Devices and choose this PC. You can also connect using its IP address.",
        ["Personalizar mi Dock"] = "Customize my Dock",
        ["Código de enlace"] = "Pairing code",
        ["Nuevo código"] = "New code",
        ["Caduca cada cinco minutos y después de enlazar."] = "Expires every five minutes and after pairing.",
        ["Puerto: {0}"] = "Port: {0}",
        ["{0} · copiar"] = "{0} · copy",
        ["Al abrir por primera vez, permite Phone Dock en redes privadas en el Firewall de Windows. No abras puertos en el router."] = "On first launch, allow Phone Dock on private networks in Windows Firewall. Do not open router ports.",
        ["Tu espacio. Tus acciones."] = "Your space. Your actions.",
        ["Los cambios se comparten con tu iPhone. Haz clic en una tarjeta para personalizarla."] = "Changes are shared with your iPhone. Click a card to customize it.",
        ["+ Agregar acción"] = "+ Add action",
        ["Página {0} · {1}/24 acciones"] = "Page {0} · {1}/24 actions",
        ["Personalizar"] = "Customize",
        ["Quitar"] = "Remove",
        ["¿Quitar {0} del Dock?"] = "Remove {0} from the Dock?",
        ["Esta primera versión admite hasta 24 acciones."] = "This preview supports up to 24 actions.",
        ["Tus dispositivos autorizados para controlar este PC."] = "Your devices authorized to control this PC.",
        ["Credencial protegida por Windows"] = "Credential protected by Windows",
        ["Olvidar dispositivo"] = "Forget device",
        ["¿Revocar el acceso de {0}?"] = "Revoke access for {0}?",
        ["Todavía no hay dispositivos. Usa el código de Inicio para enlazar tu iPhone."] = "No devices yet. Use the code on Home to pair your iPhone.",
        ["Actualizar lista"] = "Refresh list",
        ["Hazlo tuyo."] = "Make it yours.",
        ["Un poco de color. Mucho más tú."] = "A little color. A lot more you.",
        ["Océano"] = "Ocean",
        ["Atardecer"] = "Sunset",
        ["Bosque"] = "Forest",
        ["Grafito"] = "Graphite",
        ["Modo oscuro"] = "Dark mode",
        ["Iconos extragrandes"] = "Extra-large icons",
        ["Esquinas suaves"] = "Soft corners",
        ["La apariencia se guarda en este PC. Tu iPhone conserva su propia paleta."] = "Appearance is saved on this PC. Your iPhone keeps its own palette.",
        ["Tu PC y tu iPhone, conectados directamente."] = "Your PC and iPhone, connected directly.",
        ["Local. Personal. Sin suscripciones."] = "Local. Personal. No subscriptions.",
        ["Windows 11 · versión 0.3.1 · primera versión para pruebas"] = "Windows 11 · version 0.3.1 · preview",
        ["Brillo: pantallas compatibles con WMI, normalmente las integradas. Maximizar no equivale al modo de pantalla completa de todas las apps. Ocultar minimiza la ventana. Atajos de Apple y Recientes no están disponibles en esta versión."] = "Brightness works on WMI-compatible displays, usually built-in ones. Maximizing is not the same as full screen in every app. Hide minimizes the window. Apple Shortcuts and Recents are not available in this version.",
        ["Usa una red privada de confianza. El código protege el enlace y las órdenes se autentican. No hay nube ni telemetría propia. No se pueden controlar ventanas del sistema o aplicaciones ejecutadas como administrador."] = "Use a trusted private network. The code protects pairing and commands are authenticated. No cloud or first-party telemetry. System windows and applications running as administrator cannot be controlled.",
        ["La detección automática no está disponible. Usa la dirección IP que aparece en Inicio."] = "Automatic discovery is unavailable. Use the IP address shown on Home.",
        ["No se pudo abrir la conexión: {0}"] = "Could not start the connection: {0}",
        ["Idioma"] = "Language",
        ["Idioma de la app"] = "App language",
        ["Usar idioma del sistema"] = "Follow system",
        ["Se aplica al instante en este PC. Tus acciones y dispositivos enlazados no cambian."] = "Applies immediately on this PC. Your actions and paired devices stay unchanged.",
        ["Personalizar acción · Phone Dock"] = "Customize action · Phone Dock",
        ["Un toque muy tuyo."] = "A touch of you.",
        ["Nombre"] = "Name",
        ["Tipo de acción"] = "Action type",
        ["Aplicación"] = "Application",
        ["Sitio web"] = "Website",
        ["Texto"] = "Text",
        ["Nueva acción"] = "New action",
        ["Archivo .exe / .lnk, URL o texto"] = ".exe / .lnk file, URL or text",
        ["Elegir aplicación…"] = "Choose application…",
        ["Aplicaciones y accesos directos|*.exe;*.lnk"] = "Applications and shortcuts|*.exe;*.lnk",
        ["Emoji (vacío para mostrar la imagen)"] = "Emoji (leave empty to show the image)",
        ["Elegir imagen…"] = "Choose image…",
        ["Imágenes|*.png;*.jpg;*.jpeg"] = "Images|*.png;*.jpg;*.jpeg",
        ["Elige una imagen de menos de 10 MB."] = "Choose an image smaller than 10 MB.",
        ["Imagen preparada. Guarda para aplicarla."] = "Image ready. Save to apply it.",
        ["Color hexadecimal"] = "Hex color",
        ["Página del Dock"] = "Dock page",
        ["Guardar acción"] = "Save action",
        ["Cancelar"] = "Cancel",
        ["Escribe un nombre y un destino."] = "Enter a name and a target.",
        ["Usa un color de seis dígitos, como 6650D8."] = "Use a six-digit color, such as 6650D8.",
        ["Selecciona una aplicación .exe o un acceso directo .lnk existente."] = "Choose an existing .exe application or .lnk shortcut.",
        ["Escribe una dirección que empiece por https:// o http://."] = "Enter an address starting with https:// or http://.",
        ["La imagen es demasiado compleja. Elige un icono más sencillo."] = "This image is too complex. Choose a simpler icon.",
        ["Acción inválida."] = "Invalid action.",
        ["Parámetros inválidos."] = "Invalid parameters.",
        ["La aplicación ya no está en tu Dock."] = "The application is no longer in your Dock.",
        ["No se encuentra la aplicación seleccionada."] = "The selected application was not found.",
        ["Solo se permiten enlaces HTTP o HTTPS."] = "Only HTTP and HTTPS links are allowed.",
        ["Este monitor no permite ajustar el brillo por WMI."] = "This monitor does not support brightness adjustment through WMI.",
        ["No hay una ventana activa."] = "There is no active window.",
        ["Control de ventana inválido."] = "Invalid window control.",
        ["Acción de portapapeles inválida."] = "Invalid clipboard action.",
        ["El texto es demasiado largo."] = "The text is too long.",
        ["Atajos de Apple no está disponible en Windows. Agrega una aplicación o un acceso directo .lnk."] = "Apple Shortcuts is not available on Windows. Add an application or .lnk shortcut.",
        ["Recientes todavía no está disponible en Windows; agrega la app a tu Dock."] = "Recents is not available on Windows yet; add the app to your Dock.",
        ["Acción no compatible."] = "Unsupported action.",
        ["Valor fuera de rango."] = "Value out of range.",
        ["Windows bloqueó la entrada. No se pueden controlar ventanas elevadas o de seguridad."] = "Windows blocked input. Elevated and security windows cannot be controlled.",
        ["Esta versión de Phone Dock requiere Windows 11 para el emparejamiento seguro."] = "This version of Phone Dock requires Windows 11 for secure pairing.",
        ["Phone Dock ya está abierto. Busca su ventana en la barra de tareas."] = "Phone Dock is already open. Find its window on the taskbar.",
        ["No se pudo iniciar Phone Dock. Tus archivos se conservaron.\n\n{0}"] = "Could not start Phone Dock. Your files were preserved.\n\n{0}",
        ["No se pudo leer {0}."] = "Could not read {0}.",
        ["Clave P-256 inválida."] = "Invalid P-256 key.",
        ["Versión de protocolo no compatible."] = "Unsupported protocol version.",
        ["Solicitud duplicada rechazada."] = "Duplicate request rejected.",
        ["Mensaje no compatible."] = "Unsupported message.",
        ["Demasiados intentos. Espera 30 segundos."] = "Too many attempts. Wait 30 seconds.",
        ["El código es incorrecto o ha caducado."] = "The code is incorrect or has expired.",
        ["Elimina un dispositivo antes de enlazar otro."] = "Remove a device before pairing another.",
        ["El catálogo supera el tamaño permitido."] = "The catalog exceeds the size limit.",
        ["Tamaño de mensaje inválido."] = "Invalid message size.",
        ["Mensaje inválido."] = "Invalid message.",
        ["Explorador"] = "File Explorer",
        ["Bloc de notas"] = "Notepad",
        ["Un poco de magia"] = "A little magic",
    };
}
